
[standard]
    filename = 'data/geo_names.kml'
[standard.geo_names]
    0 = 'cont_europe'
    1 = 'sahara'
    2 = 'arabian_peninsula'
    3 = 'far_east_deserts'
    4 = 'persia'
    5 = 'india'

[arctic]
    filename = 'data/geo_names_arctic.kml'
[arctic.geo_names]
    0 = 'cont_europe'
    1 = 'north_america_w'
    2 = 'north_america_e'
    3 = 'far_east_deserts'
    4 = 'persia'
    5 = 'russian_east'

[atlantic]
    filename = 'data/geo_names_atlantic.kml'
[atlantic.geo_names]
    0 = 'cont_europe'
    1 = 'africa'
    2 = 'arabian_peninsula'
    3 = 'south_america'
    4 = 'persia'
    5 = 'north_america'
    

[fire]
    filename = 'data/geo_names_fire.kml'
[fire.geo_names]
    0 = 'cont_europe'
    1 = 'western_canada'
    2 = 'eastern_canada'
    3 = 'russian_far_east'
    
[fire2]
    filename = 'data/geo_names_fire2.kml'
[fire2.geo_names]
    0 = 'cont_europe'
    1 = 'africa'
    2 = 'north_america'
    3 = 'russian_far_east'

[fire3]
    filename = 'data/geo_names_fire3.kml'
[fire3.geo_names]
    0 = 'cont_europe'
    1 = 'africa'
    2 = 'na_excl_west'
    3 = 'russian_far_east'
    4 = 'na_west_coast'

[south]
    filename = 'data/geo_names_south.kml'
[south.geo_names]
    0 = 'south_america'
    1 = 'africa'
    2 = 'australia'
    3 = 'new_zealand'
